const mongoose = require("mongoose");
require("dotenv").config();

// Connect to MongoDB
mongoose
  .connect(process.env.MONGODB_URI || "mongodb://localhost:27017/iro-library")
  .then(() => console.log("Connected to MongoDB"))
  .catch((err) => console.error("MongoDB connection error:", err));

// Book Schema (simplified version)
const bookSchema = new mongoose.Schema(
  {
    title: String,
    subtitle: String,
    authors: [String],
    isbn: String,
    isbn13: String,
    publisher: String,
    publishedDate: String,
    language: String,
    pages: Number,
    description: String,
    categories: [String],
    tags: [String],
    coverImage: String,
    thumbnailImage: String,
    format: {
      type: String,
      enum: ["physical", "digital", "both"],
      default: "physical",
    },
    digitalFormats: [String],
    fileUrl: String,
    audioUrl: String,
    totalCopies: Number,
    availableCopies: Number,
    location: {
      shelf: String,
      section: String,
      floor: String,
    },
    acquisitionInfo: {
      acquisitionDate: Date,
      source: String,
      cost: Number,
      donor: String,
      notes: String,
    },
    condition: {
      type: String,
      enum: ["excellent", "good", "fair", "poor", "damaged"],
      default: "good",
    },
    rating: {
      average: { type: Number, default: 0 },
      count: { type: Number, default: 0 },
    },
    statistics: {
      views: { type: Number, default: 0 },
      likes: { type: Number, default: 0 },
      comments: { type: Number, default: 0 },
      shares: { type: Number, default: 0 },
      borrows: { type: Number, default: 0 },
    },
    isActive: { type: Boolean, default: true },
    isFeatured: { type: Boolean, default: false },
    metadata: {
      addedBy: mongoose.Schema.Types.ObjectId,
      lastModifiedBy: mongoose.Schema.Types.ObjectId,
      addedAt: { type: Date, default: Date.now },
      lastModifiedAt: { type: Date, default: Date.now },
    },
  },
  {
    timestamps: true,
  }
);

const Book = mongoose.model("Book", bookSchema);

// Sample books data
const sampleBooks = [
  {
    title: "The Great Gatsby",
    authors: ["F. Scott Fitzgerald"],
    isbn: "9780743273565",
    isbn13: "9780743273565",
    publisher: "Scribner",
    publishedDate: "2004-09-30",
    language: "English",
    pages: 180,
    description: "A classic American novel set in the Jazz Age",
    categories: ["Fiction", "Classic Literature"],
    tags: ["american literature", "jazz age", "tragedy"],
    format: "physical",
    totalCopies: 5,
    availableCopies: 3,
    location: { shelf: "A1", section: "Fiction", floor: "1" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "purchase",
      cost: 15.99,
    },
    condition: "good",
    isActive: true,
    isFeatured: true,
  },
  {
    title: "To Kill a Mockingbird",
    authors: ["Harper Lee"],
    isbn: "9780061120084",
    isbn13: "9780061120084",
    publisher: "Harper Perennial",
    publishedDate: "2006-05-23",
    language: "English",
    pages: 376,
    description: "A gripping tale of racial injustice and lost innocence",
    categories: ["Fiction", "Classic Literature"],
    tags: ["racism", "justice", "coming of age"],
    format: "physical",
    totalCopies: 8,
    availableCopies: 6,
    location: { shelf: "A2", section: "Fiction", floor: "1" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "purchase",
      cost: 14.99,
    },
    condition: "excellent",
    isActive: true,
    isFeatured: true,
  },
  {
    title: "1984",
    authors: ["George Orwell"],
    isbn: "9780451524935",
    isbn13: "9780451524935",
    publisher: "Signet Classic",
    publishedDate: "1961-01-01",
    language: "English",
    pages: 328,
    description: "A dystopian social science fiction novel and cautionary tale",
    categories: ["Fiction", "Science Fiction", "Dystopian"],
    tags: ["dystopia", "surveillance", "totalitarianism"],
    format: "both",
    digitalFormats: ["pdf", "epub"],
    totalCopies: 10,
    availableCopies: 7,
    location: { shelf: "A3", section: "Fiction", floor: "1" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "purchase",
      cost: 13.99,
    },
    condition: "good",
    isActive: true,
    isFeatured: false,
  },
  {
    title: "Pride and Prejudice",
    authors: ["Jane Austen"],
    isbn: "9780141439518",
    isbn13: "9780141439518",
    publisher: "Penguin Classics",
    publishedDate: "2003-04-29",
    language: "English",
    pages: 480,
    description: "A romantic novel of manners",
    categories: ["Fiction", "Romance", "Classic Literature"],
    tags: ["romance", "regency", "marriage"],
    format: "physical",
    totalCopies: 6,
    availableCopies: 4,
    location: { shelf: "A4", section: "Fiction", floor: "1" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "donation",
    },
    condition: "good",
    isActive: true,
    isFeatured: false,
  },
  {
    title: "The Catcher in the Rye",
    authors: ["J.D. Salinger"],
    isbn: "9780316769174",
    isbn13: "9780316769174",
    publisher: "Little, Brown and Company",
    publishedDate: "1951-07-16",
    language: "English",
    pages: 277,
    description: "A controversial novel narrated by Holden Caulfield",
    categories: ["Fiction", "Coming of Age"],
    tags: ["teenage angst", "identity", "alienation"],
    format: "physical",
    totalCopies: 4,
    availableCopies: 2,
    location: { shelf: "A5", section: "Fiction", floor: "1" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "purchase",
      cost: 16.99,
    },
    condition: "fair",
    isActive: true,
    isFeatured: false,
  },
  {
    title: "Harry Potter and the Philosopher's Stone",
    authors: ["J.K. Rowling"],
    isbn: "9780747532699",
    isbn13: "9780747532699",
    publisher: "Bloomsbury",
    publishedDate: "1997-06-26",
    language: "English",
    pages: 223,
    description: "The first book in the Harry Potter series",
    categories: ["Fiction", "Fantasy", "Children"],
    tags: ["magic", "wizards", "adventure"],
    format: "both",
    digitalFormats: ["pdf", "epub", "audiobook"],
    totalCopies: 12,
    availableCopies: 8,
    location: { shelf: "B1", section: "Fantasy", floor: "1" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "purchase",
      cost: 12.99,
    },
    condition: "excellent",
    isActive: true,
    isFeatured: true,
  },
  {
    title: "The Lord of the Rings: The Fellowship of the Ring",
    authors: ["J.R.R. Tolkien"],
    isbn: "9780547928210",
    isbn13: "9780547928210",
    publisher: "Houghton Mifflin Harcourt",
    publishedDate: "2012-09-18",
    language: "English",
    pages: 423,
    description: "The first volume of The Lord of the Rings epic",
    categories: ["Fiction", "Fantasy", "Adventure"],
    tags: ["fantasy", "epic", "middle-earth"],
    format: "physical",
    totalCopies: 7,
    availableCopies: 5,
    location: { shelf: "B2", section: "Fantasy", floor: "1" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "purchase",
      cost: 18.99,
    },
    condition: "good",
    isActive: true,
    isFeatured: true,
  },
  {
    title: "The Hobbit",
    authors: ["J.R.R. Tolkien"],
    isbn: "9780547928227",
    isbn13: "9780547928227",
    publisher: "Houghton Mifflin Harcourt",
    publishedDate: "2012-09-18",
    language: "English",
    pages: 300,
    description: "A fantasy novel about Bilbo Baggins' adventure",
    categories: ["Fiction", "Fantasy", "Adventure"],
    tags: ["fantasy", "adventure", "dragons"],
    format: "both",
    digitalFormats: ["pdf", "epub"],
    totalCopies: 9,
    availableCopies: 6,
    location: { shelf: "B3", section: "Fantasy", floor: "1" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "purchase",
      cost: 16.99,
    },
    condition: "excellent",
    isActive: true,
    isFeatured: false,
  },
  {
    title: "Dune",
    authors: ["Frank Herbert"],
    isbn: "9780441172719",
    isbn13: "9780441172719",
    publisher: "Ace",
    publishedDate: "1990-08-01",
    language: "English",
    pages: 688,
    description: "A science fiction novel set on the desert planet Arrakis",
    categories: ["Fiction", "Science Fiction"],
    tags: ["space opera", "ecology", "politics"],
    format: "physical",
    totalCopies: 5,
    availableCopies: 3,
    location: { shelf: "C1", section: "Science Fiction", floor: "1" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "purchase",
      cost: 19.99,
    },
    condition: "good",
    isActive: true,
    isFeatured: true,
  },
  {
    title: "Fahrenheit 451",
    authors: ["Ray Bradbury"],
    isbn: "9781451673319",
    isbn13: "9781451673319",
    publisher: "Simon & Schuster",
    publishedDate: "2012-01-10",
    language: "English",
    pages: 249,
    description: "A dystopian novel about a future where books are banned",
    categories: ["Fiction", "Science Fiction", "Dystopian"],
    tags: ["censorship", "books", "dystopia"],
    format: "both",
    digitalFormats: ["pdf", "epub"],
    totalCopies: 6,
    availableCopies: 4,
    location: { shelf: "C2", section: "Science Fiction", floor: "1" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "purchase",
      cost: 15.99,
    },
    condition: "good",
    isActive: true,
    isFeatured: false,
  },
  {
    title: "Brave New World",
    authors: ["Aldous Huxley"],
    isbn: "9780060850524",
    isbn13: "9780060850524",
    publisher: "Harper Perennial",
    publishedDate: "2006-10-17",
    language: "English",
    pages: 288,
    description: "A dystopian novel set in a futuristic society",
    categories: ["Fiction", "Science Fiction", "Dystopian"],
    tags: ["dystopia", "technology", "society"],
    format: "physical",
    totalCopies: 4,
    availableCopies: 2,
    location: { shelf: "C3", section: "Science Fiction", floor: "1" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "donation",
    },
    condition: "fair",
    isActive: true,
    isFeatured: false,
  },
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    authors: ["Douglas Adams"],
    isbn: "9780345391803",
    isbn13: "9780345391803",
    publisher: "Del Rey",
    publishedDate: "1995-09-27",
    language: "English",
    pages: 224,
    description: "A comedic science fiction series",
    categories: ["Fiction", "Science Fiction", "Comedy"],
    tags: ["humor", "space travel", "satire"],
    format: "both",
    digitalFormats: ["pdf", "epub", "audiobook"],
    totalCopies: 8,
    availableCopies: 6,
    location: { shelf: "C4", section: "Science Fiction", floor: "1" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "purchase",
      cost: 14.99,
    },
    condition: "good",
    isActive: true,
    isFeatured: true,
  },
  {
    title: "The Art of War",
    authors: ["Sun Tzu"],
    isbn: "9781599869773",
    isbn13: "9781599869773",
    publisher: "SmarterComics",
    publishedDate: "2012-09-04",
    language: "English",
    pages: 273,
    description: "An ancient Chinese military treatise",
    categories: ["Non-Fiction", "Philosophy", "Military"],
    tags: ["strategy", "philosophy", "warfare"],
    format: "physical",
    totalCopies: 3,
    availableCopies: 2,
    location: { shelf: "D1", section: "Non-Fiction", floor: "2" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "purchase",
      cost: 12.99,
    },
    condition: "excellent",
    isActive: true,
    isFeatured: false,
  },
  {
    title: "Sapiens: A Brief History of Humankind",
    authors: ["Yuval Noah Harari"],
    isbn: "9780062316110",
    isbn13: "9780062316110",
    publisher: "Harper",
    publishedDate: "2015-02-10",
    language: "English",
    pages: 443,
    description: "A narrative of humanity's creation and evolution",
    categories: ["Non-Fiction", "History", "Anthropology"],
    tags: ["evolution", "civilization", "history"],
    format: "both",
    digitalFormats: ["pdf", "epub", "audiobook"],
    totalCopies: 7,
    availableCopies: 5,
    location: { shelf: "D2", section: "Non-Fiction", floor: "2" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "purchase",
      cost: 24.99,
    },
    condition: "excellent",
    isActive: true,
    isFeatured: true,
  },
  {
    title: "Thinking, Fast and Slow",
    authors: ["Daniel Kahneman"],
    isbn: "9780374533557",
    isbn13: "9780374533557",
    publisher: "Farrar, Straus and Giroux",
    publishedDate: "2011-10-25",
    language: "English",
    pages: 499,
    description: "A psychology book about decision-making",
    categories: ["Non-Fiction", "Psychology", "Behavioral Science"],
    tags: ["psychology", "decision making", "cognitive bias"],
    format: "physical",
    totalCopies: 5,
    availableCopies: 3,
    location: { shelf: "D3", section: "Non-Fiction", floor: "2" },
    acquisitionInfo: {
      acquisitionDate: new Date(),
      source: "purchase",
      cost: 22.99,
    },
    condition: "good",
    isActive: true,
    isFeatured: true,
  },
];

async function seedBooks() {
  try {
    // Clear existing books (optional)
    console.log("Clearing existing books...");
    await Book.deleteMany({});

    // Insert new books
    console.log("Inserting sample books...");
    const insertedBooks = await Book.insertMany(sampleBooks);

    console.log(`Successfully inserted ${insertedBooks.length} books!`);

    // Display summary
    const totalBooks = await Book.countDocuments({});
    const activeBooks = await Book.countDocuments({ isActive: true });
    const featuredBooks = await Book.countDocuments({ isFeatured: true });

    console.log("\n--- DATABASE SUMMARY ---");
    console.log(`Total books: ${totalBooks}`);
    console.log(`Active books: ${activeBooks}`);
    console.log(`Featured books: ${featuredBooks}`);
    console.log("------------------------\n");
  } catch (error) {
    console.error("Error seeding books:", error);
  } finally {
    mongoose.connection.close();
  }
}

seedBooks();
